### ISSUE TITLE
Add SBOM definition to Cyber Domain

### ISSUE THREAD

**Issue by sparrell** [niemopen/niem-model#19]
Add SBOM = "Software Bill of Materials" to cyber domain appinfo:LocalTerm to be on par with the other acronyms defined there.
Note this issue was created as a very simple change to test the author's ability to create a pull request, etc. Albeit it is a valid need.

**Comment by sparrell** [comment]
Please assign to me (sparrell).

**Comment by cdmgtri** [comment]
Thanks!  Since the Cyber domain is currently inactive, we'll hold this issue and pull request so it can be reviewed by the Harmonization Subcommittee for 6.0.

CSVs and JSON context information are updated by tools.

**Comment by sparrell** [comment]
@cdmgtri wrt "Cyber domain is currently inactive": Isn't it true that all domains are inactive? So will this be the process for everything? Does even the harmonization committee meet? I don't see anything on https://lists.oasis-open-projects.org/g/niemopen-nbactsc/calendar.

**Comment by cdmgtri** [comment]
We have stewards to whom we can reach out to with questions or feedback for most of the domains.  The Cyber domain is not one of those domains at this time.

The list of active / inactive domains is available from the [nbac-admin repo](https://github.com/niemopen/nbac-admin).  See the spreadsheet under the `roster` folder, Harmonization tab.

**Comment by cdmgtri** [comment]
The Harmonization Subcommittee recommends approval of this proposal.
