### ISSUE TITLE
Add Publication Process Project Note link to Contributing Guidelines

### ISSUE THREAD

**Issue by sparrell** [niemopen/niem-model#21]
Add some words and a link for https://github.com/niemopen/ntac-admin/blob/main/project-notes/docs/niem-pubs-v1.0-pn01/niem-pubs-v1.0-pn01.md to https://github.com/niemopen/niem-model/blob/main/CONTRIBUTING.md#how-to-contribute

**Comment by cdmgtri** [comment]
Merged into the dev branch for 6.0.
