### ISSUE TITLE
JSON Adaptors

### ISSUE THREAD

**Issue by sparrell** [niemopen/niem-model#28]
Currently the NIEM Model can only have XML adaptors. Eg http://niem.github.io/reference/concepts/adapter/ doesn't show it, but all the boxes in that first picture currently must be XML.

For example, NIEM does not have an adaptor for STIX because STIX is specified in JSON.

The proposal is to allow JSON adaptors for JSON NIEM elements adapted from external JSON specifications like STIX, CACAO, IoB, OpenC2, etc.

**Comment by cdmgtri** [comment]
Discussed in the NTAC and agreed that this issue could be closed on 2023-06-27.  

https://github.com/niemopen/ntac-admin/blob/main/meetings/docs/2023-06-27-minutes.md 

NIEM supports leveraging external standards as-is in messages through the use of adapters. JSON adapters could be constructed similar to the XML ones. Individual IEPDs / message specifications can bring in their own external standards as needed.  The NTAC will continue to look at if there are better ways to support JSON external standards without the use of adapters.
