### ISSUE TITLE
STIX Adaptor

### ISSUE THREAD

**Issue by sparrell** [niemopen/niem-model#29]
STIX (https://www.oasis-open.org/standard/6426/) is sort of in NIEM 5.2 using by using loose manual copying of some of the needed STIX objects. The root issue is NIEM is XML and STIX is JSON. 

STIX is a crucial part of sharing threat information in the cyber domain. It is proposed that STIX be fully support thru a STIX adaptor. This would be in support of the Cyber Subcommittee.

**Comment by cdmgtri** [comment]
Discussed in the NTAC and agreed that this issue could be closed on 2023-06-27.  

https://github.com/niemopen/ntac-admin/blob/main/meetings/docs/2023-06-27-minutes.md 

NIEM supports leveraging external standards as-is in messages through the use of adapters. JSON adapters could be constructed similar to the XML ones. Individual IEPDs / message specifications can bring in their own external standards as needed.  The NTAC will continue to look at if there are better ways to support JSON external standards without the use of adapters.
