### ISSUE TITLE
CACAO Adaptor

### ISSUE THREAD

**Issue by sparrell** [niemopen/niem-model#30]
CACAO (https://docs.oasis-open.org/cacao/security-playbooks/v1.0/security-playbooks-v1.0.html) is not currently supported in NIEM. CACAO is a crucial part of sharing cyber playbooks and it is proposed that NIEM support CACAO thru some form of adaptor. This would be in support of the Cyber Subcommittee.

Note that CACAO is specified in JSON.

**Comment by cdmgtri** [comment]
Discussed in the NTAC and agreed that this issue could be closed on 2023-06-27.  

https://github.com/niemopen/ntac-admin/blob/main/meetings/docs/2023-06-27-minutes.md 

NIEM supports leveraging external standards as-is in messages through the use of adapters. JSON adapters could be constructed similar to the XML ones. Individual IEPDs / message specifications can bring in their own external standards as needed.  The NTAC will continue to look at if there are better ways to support JSON external standards without the use of adapters.
