### ISSUE TITLE
OpenC2 Adaptor

### ISSUE THREAD

**Issue by sparrell** [niemopen/niem-model#31]
OpenC2 is a suite of specifications that enables command and control of cyber defense systems and components. It is not currently supported in NIEM and the proposal is to support it with an adaptor. This would be in support of the Cyber Subcommittee.

Note OpenC2 is specified in JSON.

**Comment by cdmgtri** [comment]
Discussed in the NTAC and agreed that this issue could be closed on 2023-06-27.  

https://github.com/niemopen/ntac-admin/blob/main/meetings/docs/2023-06-27-minutes.md 

NIEM supports leveraging external standards as-is in messages through the use of adapters. JSON adapters could be constructed similar to the XML ones. Individual IEPDs / message specifications can bring in their own external standards as needed.  The NTAC will continue to look at if there are better ways to support JSON external standards without the use of adapters.
