### ISSUE TITLE
IoB Adaptor

### ISSUE THREAD

**Issue by sparrell** [niemopen/niem-model#32]
Indicators of Behavior (IOB)(https://opencybersecurityalliance.org/iob/) is a structured representation of reusable adversary behaviors, detections of those behaviors, and correlation workflows to aid network defenders. It is proposed IoB be supported in NIEM. This would be in support of the Cyber Subcommittee.

Note IoB is specified in JSON as a STIX extension.

**Comment by cdmgtri** [comment]
Discussed in the NTAC and agreed that this issue could be closed on 2023-06-27.  

https://github.com/niemopen/ntac-admin/blob/main/meetings/docs/2023-06-27-minutes.md 

NIEM supports leveraging external standards as-is in messages through the use of adapters. JSON adapters could be constructed similar to the XML ones. Individual IEPDs / message specifications can bring in their own external standards as needed.  The NTAC will continue to look at if there are better ways to support JSON external standards without the use of adapters.
