### ISSUE TITLE
Theat Actor Context Adaptor

### ISSUE THREAD

**Issue by sparrell** [niemopen/niem-model#33]
It is proposed that Threat Actor Context (TAC)  (https://www.oasis-open.org/committees/tac/charter.php#item-4) be supported in NIEM through an adaptor. This would be in support of the Cyber Subcommittee.

TAC aims to resolve ambiguity and enable interoperability across different threat-intelligence-relevant information sources and technological solutions to support organizing what is known about threat actors and their activities. To resolve ambiguity TAC will establish a common knowledge framework that enables semantic interoperability of threat actor contextual information and will involve representation enhancements that run across the strategic, operational, and tactical intelligence levels for use by public and private sector entities defending networks and endpoints. 

Note TAC is specified in JSON as a STIX extension. It seeks to provide semantic extensions for the STIX 2.x data model thereby allowing for semantic graph representation for the CTI community

**Comment by cdmgtri** [comment]
Discussed in the NTAC and agreed that this issue could be closed on 2023-06-27.  

https://github.com/niemopen/ntac-admin/blob/main/meetings/docs/2023-06-27-minutes.md 

NIEM supports leveraging external standards as-is in messages through the use of adapters. JSON adapters could be constructed similar to the XML ones. Individual IEPDs / message specifications can bring in their own external standards as needed.  The NTAC will continue to look at if there are better ways to support JSON external standards without the use of adapters.
