### ISSUE TITLE
NCIC Code updates

### ISSUE THREAD

**Issue by aprilm99** [niemopen/niem-model#48]
NCIC Code updates from April and July 2023. The attached spreadsheets contains the changes:
[niem-facet - 04032023 - merged.xlsx](https://github.com/niemopen/niem-model/files/12551436/niem-facet.-.04032023.-.merged.xlsx)
[niem-facet.xlsx](https://github.com/niemopen/niem-model/files/12551439/niem-facet.xlsx)

in  response to email on 9/6/2023:
MDCA definition should be MD CARTS   LLC%KINGSPORT TN
MSTE definition should be MR STEEL ACQUISTION CORP%PHOENIX AZ

**Comment by cdmgtri** [comment]
Merged into the dev branch for 6.0.
