### ISSUE TITLE
Harmonize mo:MILSTD2525 Properties and Types

### ISSUE THREAD

**Issue by cchipman6** [niemopen/niem-model#58]
The data types for the MILSTD2525-B and -C are identical and can be harmonized. Keep the two properties but change their definitions to make them unique. Combine the types.

Change mo:MILSTD2525-B-SIDC-Code data definition to "A MIL-STD-2525-B symbol identification code, an alphanumeric code based on a database structure that provides the minimum elements required to construct the basic icon and/or a complete symbol. Also called SIDC."

Change mo:MILSTD2525-C-SIDC-Code data definition to "A MIL-STD-2525-C symbol identification code, an alphanumeric code based on a database structure that provides the minimum elements required to construct the basic icon and/or a complete symbol. Also called SIDC."

Combine mo:MILSTD2525-B-SIDC-Type and mo:MILSTD2525-C-SIDC-Type into a single type mo:MILSTD2525-SIDC-Type with data definition: "A data type for a MIL-STD-2525 symbol identification code, an alphanumeric code based on a database structure that provides the minimum elements required to construct the basic icon and/or a complete symbol. Also called SIDC."

Combine mo:MILSTD2525-B-SIDC-SimpleType and mo:MILSTD2525-C-SIDC-SimpleType into a single simple type mo:MILSTD2525-SIDC-SimpleType with data definition "A data type for a MIL-STD-2525 symbol identification code, an alphanumeric code based on a database structure that provides the minimum elements required to construct the basic icon and/or a complete symbol. Also called SIDC." of type xs:token with pattern: "[A-Z0-9\-]{15}" and pattern explanation "A 15-character ID with upper case letters, numbers, and hyphens."

**Comment by cdmgtri** [comment]
Merged into the dev branch for 6.0.
