### ISSUE TITLE
Inconsistent namespaces and cardinalities

### ISSUE THREAD

**Issue by cabralje** [niemopen/niem-model#86]
In /external/have/geo-oasis.xsd, there are multiple namespace URIs for prefix gml http://www.opengis.net/gml and http://www.opengis.net/gml/3.2

In /external/have/xAL.xsd, there are multiple namespace URIs for prefix xlink http://www.w3.org/1999/xlink1 and http://www.w3.org/1999/xlink

In /external/have/have.xsd, have:EmergencyDepartmentStatus/have:CommentText has conflicting multiplicities 0,1 and 0,unbounded

**Comment by Shunbah** [comment]
Dr. Scott volunteered to work this for 6.0 at today's NTAC-TSC

**Comment by iamdrscott** [comment]
This is annoying, but so far no one has described a resulting real-world problem.  Those namespaces do not belong to NIEM.  We can publish a subset schema (like we did for GML), but for now we should not rewrite the URIs in somebody else's schema document.
